// client/src/Header.vue
<template>
    <div id="nav">
    <b-navbar variant="dark" type="dark">
        <b-container>
            <b-navbar-brand to="/">InterestHub</b-navbar-brand>
                <b-navbar-nav v-if="isLoggedIn">
                    <b-nav-item to="/communities">Сообщества</b-nav-item>
                    <b-nav-item to="/hub">Хаб</b-nav-item>
                    <b-nav-item-dropdown>
                        <template #button-content>
                            <img class="pfpImg" :src="pfp" alt="Profile picture">
                        </template>
                        <b-dropdown-item to="/profile">Профиль</b-dropdown-item>
                        <b-dropdown-item>ЛС</b-dropdown-item>
                        <b-dropdown-divider/>
                        <b-dropdown-item @click="logout">Выйти</b-dropdown-item>
                    </b-nav-item-dropdown>
                </b-navbar-nav>
                <b-navbar-nav v-else>
                    <b-nav-item to="/" exact>Главная страница</b-nav-item>
                    <b-nav-item to="/login" exact>Войти</b-nav-item>
                    <b-nav-item to="/register" exact>Создать аккаунт</b-nav-item>
                </b-navbar-nav>
        </b-container>
    </b-navbar>
    </div>
</template>

<script>
export default {
    props: {
        isLoggedIn: Boolean,
        updateState: Function
    },
    name: 'Header',
    methods: {
        logout: function(){
            fetch('/logout').then(()=>{
                this.updateState();
                this.$router.push('/login');
            }
            )
            
        },
        getPfp: async function(){
            let response = await fetch('/profilepicture');
            let image = await response.blob();
            return URL.createObjectURL(image);
        }
    },
    data() {
        return { 
            pfp: null
        }
    },
    mounted(){
        this.getPfp().then(image=>this.pfp=image);
    }
}
</script>

<style scoped>
    .pfpImg{
        height: 1.2rem;
    }
</style>

// client/src/Header.jsx
import React, { useEffect } from 'react';
import {Navbar, Container, Nav, Dropdown} from 'react-bootstrap';
import { Link } from 'react-router-dom';

function NavItems({isLoggedIn, updateState}){
  const [pfp, setPfp] = React.useState(null);
  useEffect(()=>{
    if (isLoggedIn){
      fetch('/profilepicture')
        .then(response=>response.blob())
        .then(image=>setPfp(URL.createObjectURL(image)));
    }
  }, [isLoggedIn]);
  if (isLoggedIn){
    if (!pfp) return null;
    return(
      <Nav>
        <Nav.Item>
          <Nav.Link as={Link} to='/communities'>Сообщества</Nav.Link>
        </Nav.Item>
        <Nav.Item>
          <Nav.Link as={Link} to='/hub'>Хаб</Nav.Link>
        </Nav.Item>
        <Dropdown>
          <Dropdown.Toggle variant='dark'>
            <img style={{height: '30px', width: '30px'}} src={pfp} alt="Аватарка" />
          </Dropdown.Toggle>
          <Dropdown.Menu>
            <Dropdown.Item as={Link} to="/profile">Профиль</Dropdown.Item>
            <Dropdown.Item as={Link} to="#">ЛС</Dropdown.Item>
            <Dropdown.Divider/>
            <Dropdown.Item as={Link} onClick={()=> { 
                fetch('/logout') 
                  .then(()=>updateState())
              }
            } to="/">Выйти</Dropdown.Item>
          </Dropdown.Menu>
        </Dropdown>
        <Nav.Item>
        </Nav.Item>
      </Nav>
    );
  }
  else{
    return(
      <Nav>
        <Nav.Item>
          <Nav.Link as={Link} to='/login'>Войти</Nav.Link>
        </Nav.Item>
        <Nav.Item>
          <Nav.Link as={Link} to="/register">Создать аккаунт</Nav.Link>
        </Nav.Item>
      </Nav>
    );
  }
}

export default function Header({isLoggedIn, updateState}){
    return(
        <Navbar bg="dark" variant='dark'>
        <Container>
          <Navbar.Brand as={Link} to='/'>
            InterestHub
          </Navbar.Brand>
          <NavItems isLoggedIn={isLoggedIn} updateState={updateState}/>
        </Container>
      </Navbar>
    );
}
